
enum RegMem {
    Ram_Bx_Si(isize),
    Ram_Bx_Di(isize),
    Ram_Bp_Si(isize),
    Ram_Bp_Di(isize),
    Ram_Si(isize),
    Ram_Di(isize),
    Ram_Bp(isize),
    Ram_Bx(isize),
    Reg16(usize),
    Reg8(usize),
    SegReg(usize),
}

type Rel8 = i8;
type Rel16 = i16;
type FPtr = (u16, u16);
type RegMem = (AddrMode, u32);

enum OpCode {
    AAA,
    AAD(u8),
    AAM(u8),
    AAS,
    ADC(Source, Destination),
    ADD(Source, Destination),
    AND(Source, Destination),
    CALL(u16JA),
    CALLF(FPtr),
    CBW,
    CLC,
    CLD,
    CLI,
    CMC,
    CMP(Source, Source),
    CMPSB,
    CMPSW,
    CWD,
    DAA,
    DAS,
    DEC(Destination),
    DIV(Source),
    HLT,
    IDIV(Source),
    IMUL(Source),
    IN(Source),
    INC(Destination),
    INT(u8),
    INTO,
    IRET,
    JO(Rel8),
    JNO(Rel8),
    JB(Rel8),
    JNB(Rel8),
    JZ(Rel8),
    JNZ(Rel8),
    JNA(Rel8),
    JA(Rel8),
    JS(Rel8),
    JNS(Rel8),
    JP(Rel8),
    JNP(Rel8),
    JL(Rel8),
    JNL(Rel8),
    JLE(Rel8),
    JNLE(Rel8),
    JMP(Rel8),
    JMP16(Rel16),
    JMPF(FPtr),
    JAHF,
    LDS(Source, Destination),
    LEA(Source, Destination),
    LES(Source, Destination),
    LODSB,
    LODSW,
    LOOP(Rel8),
    LOOPE(Rel8),
    LOOPNE(Rel8),
    LOOPNZ(Rel8),
    LOOPZ(Rel8),
    MOV(Source, Destination),
    MOVSB,
    MOVSW,
    MUL(Source),
    NEG(Destination),
    NOP,
    NOT(Destination),
    OR(Source, Destination),
    OUT(Source),
    POP(Destination),
    POPA,
    POPF,
    PUSH(Source),
    PUSHA,
    PUSHF,
    RCL(Source, Destination), // S = 1 or CL
    RCR(Source, Destination), // S = 1 or CL
    REP, // How do I represent this?
    REPE,
    REPNE,
    REPNZ,
    REPZ,
    RET,
    RETF,
    ROL(Source, Destination),
    ROR(Source, Destination),
    SAHF,
    SAL(Source, Destination),
    SAR(Source, Destination),
    SBB(Source, Destination),
    SCASB,
    SCASW,
    SHL(Source, Destination),
    SHR(Source, Destination),
    STC,
    STD,
    STI,
    STOSB,
    STOSW,
    SUB(Source, Destination),
    TEST(Source, Source),
    XCHG(Destination, Destination),
    XLATB,
    XOR(Source, Destination),
}

