
enum OpCode {
    AAA,
    AAD,
    AAM,
    AAS,
    ADC(Source, Destination),
    ADD(Source, Destination),
    AND(Source, Destination),
    CALL(Address),
    CBW,
    CLC,
    CLD,
    CLI,
    CMC,
    CMP(Source, Source),
    CMPSB,
    CMPSW,
    CWD,
    DAA,
    DAS,
    DEC(Destination),
    DIV(Source),
    HLT,
    IDIV(Source),
    IMUL(Source),
    IN(Source),
    INC(Destination),
    INT(u8),
    INTO,
    IRET,
    JA(Address),
    // And all the jumps
    JMP(Address), // or long pointer
    JAHF,
    LDS(Source, Destination),
    LEA(Source, Destination),
    LES(Source, Destination),
    LODSB,
    LODSW,
    LOOP(Address),
    LOOPE(Address),
    LOOPNE(Address),
    LOOPNZ(Address),
    LOOPZ(Address),
    MOV(Source, Destination),
    MOVSB,
    MOVSW,
    MUL(Source),
    NEG(Destination),
    NOP,
    NOT(Destination),
    OR(Source, Destination),
    OUT(Source),
    POP(Destination),
    POPA,
    POPF,
    PUSH(Source),
    PUSHA,
    PUSHF,
    RCL(Source, Destination), // S = 1 or CL
    RCR(Source, Destination), // S = 1 or CL
    REP, // How do I represent this?
    REPE,
    REPNE,
    REPNZ,
    REPZ,
    RET,
    RETF,
    ROL(Source, Destination),
    ROR(Source, Destination),
    SAHF,
    SAL(Source, Destination),
    SAR(Source, Destination),
    SBB(Source, Destination),
    SCASB,
    SCASW,
    SHL(Source, Destination),
    SHR(Source, Destination),
    STC,
    STD,
    STI,
    STOSB,
    STOSW,
    SUB(Source, Destination),
    TEST(Source, Source),
    XCHG(Destination, Destination),
    XLATB,
    XOR(Source, Destination),
}

